# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)


2.2.0


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.randint(10, size=(2, 3, 5))


### 4. Print a.


In [4]:
print(a)

[[[1 0 7 0 5]
  [3 4 8 2 0]
  [1 7 6 5 8]]

 [[7 4 0 7 7]
  [0 7 1 6 6]
  [6 2 1 9 9]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [8]:
print(np.dot(a, b))

# no because shapes (2,3,5) and (5,2,3) not aligned: 5 (dim 2) != 2 (dim 1)

ValueError: shapes (2,3,5) and (5,2,3) not aligned: 5 (dim 2) != 2 (dim 1)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
c = b.transpose(1, 2, 0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
# print(c)
d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
print(a)
print(d)

# Each value of the a array got added up with each value of the c array

[[[1 0 7 0 5]
  [3 4 8 2 0]
  [1 7 6 5 8]]

 [[7 4 0 7 7]
  [0 7 1 6 6]
  [6 2 1 9 9]]]
[[[ 2.  1.  8.  1.  6.]
  [ 4.  5.  9.  3.  1.]
  [ 2.  8.  7.  6.  9.]]

 [[ 8.  5.  1.  8.  8.]
  [ 1.  8.  2.  7.  7.]
  [ 7.  3.  2. 10. 10.]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
e = np.multiply(a, c)




### 13. Does e equal to a? Why or why not?


In [13]:
is_equal = np.equal(e, a)
print(is_equal)

# Yes because each value == True


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)



10.0
1.0
5.3



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
f = np.empty((2, 3, 5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
for i, sub in enumerate(d):
  for j, s_sub in enumerate(sub):
    for k, val in enumerate(s_sub):
      if val > d_mean and val < d_max:
        f[i][j][k] = 75
      elif val > d_min and val < d_mean:
        f[i][j][k] = 25
      elif val == d_mean:
        f[i][j][k] = 50
      elif val == d_min:
        f[i][j][k] = 0
      elif val == d_max:
        f[i][j][k] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
print(d)
print(f)


[[[ 2.  1.  8.  1.  6.]
  [ 4.  5.  9.  3.  1.]
  [ 2.  8.  7.  6.  9.]]

 [[ 8.  5.  1.  8.  8.]
  [ 1.  8.  2.  7.  7.]
  [ 7.  3.  2. 10. 10.]]]
[[[ 25.   0.  75.   0.  75.]
  [ 25.  25.  75.  25.   0.]
  [ 25.  75.  75.  75.  75.]]

 [[ 75.  25.   0.  75.  75.]
  [  0.  75.  25.  75.  75.]
  [ 75.  25.  25. 100. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.